services:
  - type: web
    name: discord-lfg-bot
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 1